import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google"
 
import { cn } from "@/lib/utils"
import {Providers} from './providers'
import { Toaster } from "@/components/ui/toaster";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "variable",
})

export const metadata: Metadata = {
  title: "Whatsapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn(" dark min-h-screen bg-background font-sans antialiased", fontSans.variable)} >
            <Providers>
              {children}
            </Providers>
            <Toaster />
      </body>
    </html>
  );
}
